package com.zeynthedev.zeynsudoku;

import java.io.IOException;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.geometry.Pos;
import javafx.scene.control.TextField;
import javafx.scene.layout.GridPane;
import javafx.scene.text.Font;
import javafx.scene.control.Label;
import javafx.scene.Node;
import javafx.event.ActionEvent;
import javafx.scene.control.Alert;
import javafx.scene.control.ButtonType;
import javafx.animation.KeyFrame;
import javafx.animation.Timeline;
import javafx.util.Duration;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import javafx.scene.Scene;
import javafx.scene.layout.VBox;
import javafx.scene.control.Button;
import javafx.stage.Modality;

public class PrimaryController implements Initializable {

    @FXML
    private Label lblLeft1, lblLeft2, lblLeft3, lblLeft4, lblLeft5, lblLeft6, lblLeft7, lblLeft8, lblLeft9;
    
    @FXML
    private Label lblTimer, lblDifficulty;
    
    private Timeline timeline;
    private int secondsRun = 0;
    private String activeDifficulty = "Easy";
    private int hintLeft = 10;
    private int[][] currentSolution;
    
    @FXML
    private GridPane sudokuGrid;
    
    @FXML private javafx.scene.layout.VBox pauseOverlay;

    // array 2d to saving 81 box references
    private TextField[][] boardData = new TextField[9][9];

    // active/chosen number by user
    private int selected = -1;

    // saving left number indicator
    private int[] leftNum = new int[10];
    
    @FXML
    private Label lblHintCount;
    
    private int hintTotal = 10;

    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // build the UI board
        createSudokuBoard();
        // create the puzzle
        if(GameState.isContinue && SaveManager.hasSave()) {
            loadGameData();
        } else {
            actNewGame();
        }
        
        if (pauseOverlay != null) {
            pauseOverlay.setOnMouseClicked(event -> {
                actPause();
            });
        }
    }

    // bottom button logic
    @FXML
    private void actMenu() {
        // Simpan status: apakah game sedang berjalan?
        boolean wasRunning = (timeline != null && timeline.getStatus() == Timeline.Status.RUNNING);

        // Pause waktu selagi dialog muncul
        if (wasRunning) timeline.pause();
        
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.setTitle("ZeynSudoku");
        alert.setHeaderText("Return");
        alert.setContentText("Are you sure to return to main menu?");
        
        alert.showAndWait().ifPresent(response -> {
            if (response == ButtonType.OK) {
                saveCurrentGame();
                try {
                    App.setRoot("secondary"); // back to main menu
                } catch (IOException ex) {
                    System.getLogger(PrimaryController.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            } else if (timeline != null) {
                if (wasRunning) timeline.play();
            }
        });
    }

    @FXML
    private void actNewGame() {
        String difficulty = showDifficulty();
        
        //set the difficulty first
        if (difficulty != null) {
            this.activeDifficulty = difficulty;
            lblDifficulty.setText(difficulty.toUpperCase());
            
            // set the hint based on difficulty chosen
            if (difficulty.equals("Easy")) hintTotal = 10;
            else if (difficulty.equals("Medium")) hintTotal = 6;
            else hintTotal = 3;
            
            hintLeft = hintTotal;
            updateHintUI();
            
            SudokuGenerator generator = new SudokuGenerator();
            int[][] newPuzzle = generator.createPuzzle(difficulty);
            this.currentSolution = generator.getSolutionBoard();
            
            // print the puzzle on the UI
            for (int r = 0; r < 9; r++) {
                for (int c = 0; c < 9; c++) {
                    TextField box = boardData[r][c];
                    int num = newPuzzle[r][c];

                    // if it was used to play a game before, erased the past clue to write the new clues
                    box.getProperties().remove("clue");

                    if (num != 0) {
                        // if a num exist, then it's clue generated by the SudokuGen
                        box.setText(String.valueOf(num));
                        box.getProperties().put("clue", true); // set editable = false for the clue
                    } else {
                        // if 0 the it's answer box to be filled
                        box.setText("");
                    }
                }
            }

            renderBoardUI();
            
            // reset it
            secondsRun = 0;
            lblTimer.setText("00:00");
            startTimer();

            System.out.println("Game is successfully loaded!");
        }
    }

    @FXML
    private void actPause() {
        if (timeline != null) {
            if (timeline.getStatus() == Timeline.Status.RUNNING) {
                timeline.pause();
                pauseOverlay.setVisible(true);
                System.out.println("Game is paused.");
            } else {
                timeline.play();
                pauseOverlay.setVisible(false);
                System.out.println("Game is continued.");
            }
        }
    }

    @FXML
    private void actReset() {
        //pause timer for showing confirmation pop up dialog
        boolean wasRunning = false;
        if (timeline != null && timeline.getStatus() == Timeline.Status.RUNNING) {
            wasRunning = true;
            timeline.pause();
        }
        
        //show confirmation pop up dialog
        Alert alert = new Alert(Alert.AlertType.CONFIRMATION);
        alert.setTitle("Reset Confirmation");
        alert.setHeaderText("Reset Puzzle?");
        alert.setContentText("All your answers will be erased and"
                + " board will be returned to early state. Are you sure?");
        
        //get timer status to be used on lambda expression
        final boolean finalWasRunning = wasRunning;
        
        alert.showAndWait().ifPresent(response -> {
            if (response == ButtonType.OK) {
                for (int r = 0; r < 9; r++) {
                    for (int c = 0; c < 9; c++) {
                        TextField box = boardData[r][c];
                        
                        if (!box.getProperties().containsKey("clue")) {
                            box.setText("");
                        }
                    }
                }
                
                renderBoardUI();
                System.out.println("Puzzle is reset.");
            }
            if (finalWasRunning && timeline != null) {
                timeline.play();
            }
        });
    }

    @FXML
    private void actHint() {
        if (hintLeft > 0) {
            java.util.List<int[]> emptyCells = new java.util.ArrayList<>();
            
            //getting all coordinates that still empty
            for (int r = 0; r < 9; r++) {
                for (int c = 0; c < 9; c++) {
                    if (boardData[r][c].getText().isEmpty()) {
                        emptyCells.add(new int[]{r, c});
                    }
                }
            }
            
            //if they're exist, choose a random hint number
            if(!emptyCells.isEmpty()) {
                int[] target = emptyCells.get(new java.util.Random().nextInt(emptyCells.size()));
                int row = target[0];
                int col = target[1];
                
                //fill with a hint number from currentSolution
                int correctNum = currentSolution[row][col];
                boardData[row][col].setText(String.valueOf(correctNum));
                
                //mark as clue so it won't be editable
                boardData[row][col].getProperties().put("clue", true);
                
                hintLeft--;
                updateHintUI(); // Update UI angka sisa hint
                renderBoardUI(); // Update warna papan
            }
        } else {
            Alert alert = new Alert(Alert.AlertType.WARNING);
            alert.setTitle("ZeynSudoku");
            alert.setHeaderText(null);
            alert.setContentText("Your hint all are already used!");
            alert.show();
        }
    }

    @FXML
    private void actChooseNum(ActionEvent event) {
        // get element from recently clicked btn
        Node clickedBtn = (Node) event.getSource();

        selected = Integer.parseInt(clickedBtn.getUserData().toString());

        System.out.println("Num inputter changed to: " + (selected == 0 ? "Delete" : selected));
        
        renderBoardUI();
    }
    
    private void createSudokuBoard() {
        for (int row = 0; row < 9; row++) {
            for (int column = 0; column < 9; column++) {
                TextField box = new TextField();

                boardData[row][column] = box;

                box.setPrefSize(45, 45);
                box.setAlignment(Pos.CENTER);
                box.setFont(Font.font("Sytem", 18));

                box.setEditable(false);
                box.setFocusTraversable(false);

                box.setOnMouseClicked(event -> {
                    // 1. check does it a clue box or not. If yes, ignore.
                    if (box.getStyleClass().contains("clue")) {
                        return;
                    }

                    // 2. If user not choosing any number, ignore
                    if (selected == -1) {
                        return;
                    }

                    // 3. Logic to rewrite, delete, and fill
                    String numString = String.valueOf(selected);

                    if (selected == 0) {
                        // if delete chosen, delete box content
                        box.setText("");
                    } else if (box.getText().equals(numString)) {
                        // if the user click the box again with the same chosen number, the box will delete its content
                        box.setText("");
                    } else {
                        // if the box is empty or had different number, rewrite the content (the number) with currently chosen number
                        box.setText(numString);
                        box.setStyle("-fx-text-fill: #0078D7; -fx-font-weight: bold;");
                    }

                    renderBoardUI();
                    
                    // ---------------------------------------------------------
                    // Auto Switch Logic
                    // ---------------------------------------------------------
                    
                    // if selected num now was reached 0 (was filled all)
                    if (selected >= 1 && selected <= 9 && leftNum[selected] == 0) {
                        // find the next num that still had left nums to be filled
                        for (int i = 1; i<= 9; i++) {
                            int nextNum = (selected + i - 1) % 9 + 1;
                            
                            if (leftNum[nextNum] > 0) {
                                selected = nextNum; // move chooser to new num
                                System.out.println("Auto-switch to num " + selected);
                                
                                renderBoardUI();
                                break;
                            }
                        }
                    }
                });

                // border for each 3x3 domain logic
                int top = (row % 3 == 0) ? 3 : 1;
                int left = (column % 3 == 0) ? 3 : 1;
                int bottom = (row == 8) ? 3 : 1;
                int right = (column == 8) ? 3 : 1;

                // CSS styling for the box
                box.setStyle(
                        "-fx-border-color: black; "
                        + "-fx-border-width: " + top + " " + right + " " + bottom + " " + left + "; "
                        + "-fx-background-color: white; "
                        + // Basic color
                        "-fx-background-radius: 0; "
                        + // remove round corner from TextField default
                        "-fx-border-radius: 0;"
                        + // remove box padding
                        "-fx-padding: 0;"
                );

                sudokuGrid.add(box, column, row);
            }
        }
    }

    private void renderBoardUI() {
        // matrix for saving error boxes
        boolean[][] isError = new boolean[9][9];
        
        int leftBox = 0;
        boolean error = false;

        // ---------------------------------------------------------
        // BLOC 1: DATA CALCULATION (Calculate Left & Error Checking)
        // ---------------------------------------------------------
        for (int i = 1; i <= 9; i++) {
            leftNum[i] = 9;
        }

        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                String text = boardData[r][c].getText();

                if (text.isEmpty()) {
                    leftBox++;
                    continue;
                }

                int num = Integer.parseInt(text);
                leftNum[num]--;

                for (int i = 0; i < 9; i++) {
                    if (i != c && boardData[r][i].getText().equals(text)) {
                        isError[r][c] = true;
                        isError[r][i] = true;
                        error = true;
                    }
                    if (i != r && boardData[i][c].getText().equals(text)) {
                        isError[r][c] = true;
                        isError[i][c] = true;
                        error = true;
                    }
                }

                // checking the conflict with existing number on board
                int startRow = (r / 3) * 3;
                int startCol = (c / 3) * 3;
                for (int i = startRow; i < startRow + 3; i++) {
                    for (int j = startCol; j < startCol + 3; j++) {
                        if ((i != r || j != c) && boardData[i][j].getText().equals(text)) {
                            isError[r][c] = true;
                            isError[i][j] = true;
                            error = true;
                        }
                    }
                }
            }
        }

        // ---------------------------------------------------------
        // BLOK 2: UPDATE BOX VISUAL (Single Source of Style)
        // ---------------------------------------------------------
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                TextField box = boardData[r][c];
                String text = box.getText();

                // 1. Adjust Shape (3x3)
                int top = (r % 3 == 0) ? 3 : 1;
                int left = (c % 3 == 0) ? 3 : 1;
                int bottom = (r == 8) ? 3 : 1;
                int right = (c == 8) ? 3 : 1;
                String styleBorder = "-fx-border-color: black; -fx-border-width: " + top + " " + right + " " + bottom + " " + left + "; -fx-border-radius: 0; -fx-background-radius: 0; ";

                // 2. Adjust Background Color -> HIGHLIGHT IS HERE
                // Cek does this box content is equals with the chosen num
                boolean isSelectedNum = !text.isEmpty() && selected != -1 && text.equals(String.valueOf(selected));
                
                String styleBg = "-fx-background-color: white; "; // Default bg color
                
                if (isError[r][c]) {
                    // 1st Priority: Error (Light Red)
                    styleBg = "-fx-background-color: #FFCDD2; "; 
                } else if (isSelectedNum) {
                    // 2nd Priority: Selected/highlighted Num (Light Blue)
                    styleBg = "-fx-background-color: #BBDEFB; "; 
                }

                // 3. Adjust Text Color (Font)
                boolean isClue = box.getProperties().containsKey("clue");
                String styleText = isClue ? "-fx-text-fill: black; -fx-font-weight: bold;" : "-fx-text-fill: #0078D7; -fx-font-weight: bold;";

                if (isError[r][c]) {
                    // If error, font becomes bold red
                    styleText = "-fx-text-fill: #D32F2F; -fx-font-weight: bold;"; 
                }

                // 4. Apply all styling simultaneously
                box.setStyle(styleBorder + styleBg + styleText);
            }
        }

        // ---------------------------------------------------------
        // BLOK 3: UPDATE LEFT NUMBER VISUAL
        // ---------------------------------------------------------
        if (lblLeft1 != null) {
            lblLeft1.setText(String.valueOf(leftNum[1]));
            lblLeft2.setText(String.valueOf(leftNum[2]));
            lblLeft3.setText(String.valueOf(leftNum[3]));
            lblLeft4.setText(String.valueOf(leftNum[4]));
            lblLeft5.setText(String.valueOf(leftNum[5]));
            lblLeft6.setText(String.valueOf(leftNum[6]));
            lblLeft7.setText(String.valueOf(leftNum[7]));
            lblLeft8.setText(String.valueOf(leftNum[8]));
            lblLeft9.setText(String.valueOf(leftNum[9]));
        }
        
        // ---------------------------------------------------------
        // BLOK 4: WIN CONDITION (placed on last)
        // ---------------------------------------------------------
        if (leftBox == 0 && !error) {
            javafx.application.Platform.runLater(() -> {
                winPopUp();
            });
        }
    }
    
    private void winPopUp() {
        if (timeline != null) timeline.stop();
        
        Alert alert = new Alert(Alert.AlertType.INFORMATION);
        alert.setTitle("ZeynSudoku");
        alert.setHeaderText("🎉 CONGRATULATION! 🎉");
        alert.setContentText("You've solved this puzzle!");
        
        alert.showAndWait().ifPresent(response -> {
            if (response == ButtonType.OK) {
                SaveManager.deleteSave();
                try {
                    App.setRoot("secondary"); // back to main menu
                } catch (IOException ex) {
                    System.getLogger(PrimaryController.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            }
        });
    }
    
    private void startTimer() {
        // stop existing timer
        if (timeline != null) {
            timeline.stop();
        }
        
        // MENCETAK WAKTU SAAT INI KE LAYAR (Tanpa delay 1 detik)
        int min = secondsRun / 60;
        int sec = secondsRun % 60;
        lblTimer.setText(String.format("%02d:%02d", min, sec));
        
        timeline = new Timeline(new KeyFrame(Duration.seconds(1), event -> {
            secondsRun++;
            
            int minute = secondsRun / 60;
            int second = secondsRun % 60;
            
            String timeText = String.format("%02d:%02d", minute, second);
            lblTimer.setText(timeText);
        }));
        
        timeline.setCycleCount(Timeline.INDEFINITE);
        timeline.play();
    }
    
    private String showDifficulty() {
        final String[] result = {null};
        
        Stage dialog = new Stage();
        dialog.initModality(Modality.APPLICATION_MODAL);
        dialog.initStyle(StageStyle.UNDECORATED);
        
        VBox layout = new VBox(15);
        layout.setAlignment(Pos.CENTER);
        layout.setStyle("-fx-padding: 20; -fx-border-color: #333; -fx-border-width: 2; -fx-background-color: white;");
        
        Label title = new Label("Choose The Difficulty");
        title.setStyle("-fx-font-weight: bold; -fx-font-size: 18px;");
        
        Button btnEasy = new Button("Easy (10 Hint)");
        Button btnMedium = new Button("Medium (6 Hint)");
        Button btnHard = new Button("Hard (3 Hint)");
        Button btnCancel = new Button("Cancel");
        
        btnEasy.setPrefWidth(150);
        btnMedium.setPrefWidth(150);
        btnHard.setPrefWidth(150);
        
        btnEasy.setOnAction(e -> { result[0] = "Easy"; dialog.close(); });
        btnMedium.setOnAction(e -> { result[0] = "Medium"; dialog.close(); });
        btnHard.setOnAction(e -> { result[0] = "Hard"; dialog.close(); });
        btnCancel.setOnAction(e -> { dialog.close(); });
        
        layout.getChildren().addAll(title, btnEasy, btnMedium, btnHard, btnCancel);
        
        Scene scene = new Scene(layout);
        dialog.setScene(scene);
        dialog.showAndWait();
        
        return result[0];
    }
    
    private void updateHintUI(){
        if (lblHintCount != null) {
            lblHintCount.setText(hintLeft + "/" + hintTotal);
        }
    }
    
    private void saveCurrentGame() {
        int[][] currentBoard = new int[9][9];
        boolean[][] clues = new boolean[9][9];
        
        // extract num from TextField UI to array
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                String txt = boardData[r][c].getText();
                currentBoard[r][c] = txt.isEmpty() ? 0 : Integer.parseInt(txt);
                clues[r][c] = boardData[r][c].getProperties().containsKey("clue");
            }
        }
        
        SaveManager.saveGame(activeDifficulty, secondsRun, hintLeft, currentBoard, clues, currentSolution);
        System.out.println("Game successfully saved!");
    }
    
    private void loadGameData() {
        java.util.Properties props = SaveManager.loadGame();
        if (props == null) return;
        
        // return info stat
        this.activeDifficulty = props.getProperty("difficulty");
        this.secondsRun = Integer.parseInt(props.getProperty("time"));
        this.hintLeft = Integer.parseInt(props.getProperty("hint"));
        
        lblDifficulty.setText(activeDifficulty.toUpperCase());
        
        if (activeDifficulty.equals("Easy")) hintTotal = 10;
        else if (activeDifficulty.equals("Medium")) hintTotal = 6;
        else hintTotal = 3;
        
        updateHintUI();
        
        // load String that turned as csv
        String[] arrBoard = props.getProperty("board").split(",");
        String[] arrClues = props.getProperty("clues").split(",");
        String[] arrSol = props.getProperty("solution").split(",");
        
        currentSolution = new int[9][9];
        int index = 0;
        
        // 3. fill it again to UI board
        for (int r = 0; r < 9; r++) {
            for (int c = 0; c < 9; c++) {
                TextField box = boardData[r][c];
                box.getProperties().remove("clue"); // clear it first

                int num = Integer.parseInt(arrBoard[index]);
                boolean isClue = arrClues[index].equals("1");
                currentSolution[r][c] = Integer.parseInt(arrSol[index]);

                if (num != 0) {
                    box.setText(String.valueOf(num));
                    if (isClue) {
                        box.getProperties().put("clue", true);
                    } else {
                        // If not clue, So it was user answer (give blue color)
                        box.setStyle("-fx-text-fill: #0078D7; -fx-font-weight: bold; -fx-padding: 0;");
                    }
                } else {
                    box.setText("");
                }
                index++;
            }
        }

        renderBoardUI();
        startTimer(); // Timer akan otomatis melanjutkan dari secondsRun yang di-load
        System.out.println("Game berhasil di-load!");
    }
}
